### PR TITLE
fix #7 add missing eraseBlock()

### LINKED ISSUE #7: EraseBlock() no longer works for 25Q16
With the 3.0 release standardizing functions across multiple devices, it looks like I encountered some fallout.

EraseBlock() continues to be a function which compiles, although it no longer erases a block on the ItsyBitsy M4’s 25Q16 QSPI memory.

This wouldn’t be so bad, except a loop of eraseSector() calls is about 10 times slower.

I would like to request that the functionality be brought back, as it was quite useful.

### PR DESCRIPTION
**Pull request by hathach**
#7

### CODE REVIEW

**Comment by hathach** [comment]
Hmm, I don't know why Travis failed, ` arduino:samd` is also installed, it should be able to find the `sam.h`

```
########################################################################
flash_erase.ino: ✖
----------------------------- DEBUG OUTPUT -----------------------------
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
In file included from sketch/flash_erase.ino.cpp:1:0:
/home/travis/.arduino15/packages/adafruit/hardware/samd/1.5.0/cores/arduino/Arduino.h:48:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
exit status 1
```

**Comment by makermelissa** [comment]
Cache needs to be clear and the build restarted.

**Comment by hathach** [comment]
> Cache needs to be clear and the build restarted.

yeaahhh, it works, thank you very much :)

**Comment by ladyada** [comment]
@dshadoff please try this

**Pull request merged**
